name: Workflow - Pull Request

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run prettier
        run: npx prettier --check .

  validate-entry:
    name: Validate entries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate entry
        run: ./.github/workflows/validate-entry.yml

  check-file-changes:
    name: Check file changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check file changes
        run: ./.github/workflows/check-file-changes.yml
